"use client";

import { motion, AnimatePresence } from "framer-motion";
import {
  Clock,
  Flame,
  ChefHat,
  Users,
  Globe,
  Bookmark,
  BookmarkCheck,
  Share2,
  Printer,
  Check,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { GeneratedRecipe } from "@/lib/types";
import { formatTime, formatCalories, getDifficultyColor, getDifficultyPercent } from "@/lib/utils";
import NutritionChart from "./NutritionChart";
import RefineButtons from "./RefineButtons";

interface RecipeDetailProps {
  recipe: GeneratedRecipe;
  recipeId?: string;
  onRefine: (recipe: GeneratedRecipe) => void;
}

export default function RecipeDetail({ recipe, recipeId, onRefine }: RecipeDetailProps) {
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleSave = async () => {
    if (!recipeId) {
      toast.info("Sign in to save recipes");
      return;
    }
    try {
      const res = await fetch("/api/save-recipe", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ recipeId }),
      });
      const data = await res.json();
      setSaved(data.saved);
      toast.success(data.saved ? "Recipe saved!" : "Recipe removed from saved");
    } catch {
      toast.error("Failed to save recipe");
    }
  };

  const handleShare = async () => {
    const text = `Check out this recipe for ${recipe.title} generated by FlavorLens AI!`;
    if (navigator.share) {
      await navigator.share({ title: recipe.title, text });
    } else {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success("Link copied!");
    }
  };

  const handlePrint = () => window.print();

  const meta = [
    { icon: Clock, label: "Prep", value: formatTime(recipe.prepTime) },
    { icon: Flame, label: "Cook", value: formatTime(recipe.cookTime) },
    { icon: ChefHat, label: "Level", value: recipe.difficulty },
    { icon: Users, label: "Serves", value: String(recipe.servings) },
    { icon: Globe, label: "Cuisine", value: recipe.cuisine },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-6"
    >
      {/* Header */}
      <div className="p-6 rounded-2xl glass border border-white/8">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div className="flex-1">
            <h2 className="text-2xl sm:text-3xl font-bold gradient-text mb-2">
              {recipe.title}
            </h2>
            <p className="text-muted-foreground text-sm leading-relaxed">
              {recipe.description}
            </p>
          </div>
          <div className="flex-shrink-0 flex flex-col sm:flex-row gap-2">
            <button
              onClick={handleSave}
              className={`p-2.5 rounded-xl border transition-all duration-200 ${
                saved
                  ? "border-orange-500/50 bg-orange-500/10 text-orange-400"
                  : "border-white/10 bg-white/5 text-muted-foreground hover:text-foreground"
              }`}
            >
              {saved ? <BookmarkCheck className="w-4 h-4" /> : <Bookmark className="w-4 h-4" />}
            </button>
            <button
              onClick={handleShare}
              className="p-2.5 rounded-xl border border-white/10 bg-white/5 text-muted-foreground hover:text-foreground transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-green-400" /> : <Share2 className="w-4 h-4" />}
            </button>
            <button
              onClick={handlePrint}
              className="hidden sm:block p-2.5 rounded-xl border border-white/10 bg-white/5 text-muted-foreground hover:text-foreground transition-colors"
            >
              <Printer className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Calories badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full gradient-brand text-white text-sm font-semibold shadow-lg shadow-orange-500/20 mb-4">
          <Flame className="w-4 h-4" />
          {formatCalories(recipe.calories)} calories per serving
        </div>

        {/* Meta grid */}
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
          {meta.map(({ icon: Icon, label, value }) => (
            <div key={label} className="flex flex-col items-center py-3 rounded-xl bg-white/5 border border-white/5">
              <Icon className="w-4 h-4 text-orange-400 mb-1" />
              <span className={`text-sm font-semibold ${label === "Level" ? getDifficultyColor(value) : ""}`}>
                {value}
              </span>
              <span className="text-[11px] text-muted-foreground">{label}</span>
            </div>
          ))}
        </div>

        {/* Difficulty bar */}
        <div className="mt-4">
          <div className="flex justify-between text-xs text-muted-foreground mb-1">
            <span>Difficulty</span>
            <span className={getDifficultyColor(recipe.difficulty)}>{recipe.difficulty}</span>
          </div>
          <div className="h-1.5 bg-white/10 rounded-full overflow-hidden">
            <motion.div
              className="h-full gradient-brand rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${getDifficultyPercent(recipe.difficulty)}%` }}
              transition={{ duration: 1, delay: 0.5 }}
            />
          </div>
        </div>

        {/* Tags */}
        {recipe.tags?.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-4">
            {recipe.tags.map((tag) => (
              <span key={tag} className="px-2.5 py-1 rounded-lg bg-white/5 text-xs text-muted-foreground">
                {tag}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Refine buttons */}
      <RefineButtons recipe={recipe} onRefine={onRefine} />

      {/* Two columns on desktop */}
      <div className="grid lg:grid-cols-2 gap-6">
        {/* Ingredients */}
        <div className="p-6 rounded-2xl glass border border-white/8">
          <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
            <span className="w-1 h-5 rounded-full gradient-brand" />
            Ingredients
          </h3>
          <div className="space-y-2">
            {recipe.ingredients.map((ing, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.04 }}
                className="flex items-center gap-3 py-2 border-b border-white/5 last:border-0 group"
              >
                <div className="w-1.5 h-1.5 rounded-full bg-orange-400 flex-shrink-0 group-hover:scale-150 transition-transform" />
                <span className="flex-1 text-sm font-medium">{ing.name}</span>
                <span className="text-sm text-muted-foreground flex-shrink-0">
                  {ing.amount} {ing.unit}
                </span>
              </motion.div>
            ))}
          </div>

          {/* Alternative ingredients */}
          {(recipe.alternativeIngredients?.length ?? 0) > 0 && (
            <div className="mt-4 pt-4 border-t border-white/5">
              <h4 className="text-sm font-semibold text-muted-foreground mb-3">
                Substitutions
              </h4>
              <div className="space-y-2">
                {recipe.alternativeIngredients?.map((alt, i) => (
                  <div key={i} className="text-xs">
                    <span className="text-muted-foreground">{alt.original}: </span>
                    <span className="text-foreground">{alt.alternatives.join(", ")}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Nutrition */}
        <NutritionChart nutrition={recipe.nutrition} />
      </div>

      {/* Instructions */}
      <div className="p-6 rounded-2xl glass border border-white/8">
        <h3 className="text-lg font-bold mb-6 flex items-center gap-2">
          <span className="w-1 h-5 rounded-full gradient-brand" />
          Instructions
        </h3>
        <div className="space-y-4">
          {recipe.instructions.map((step, i) => (
            <motion.div
              key={step.step}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07 }}
              className="flex gap-4 group"
            >
              <div className="flex-shrink-0 w-8 h-8 rounded-full gradient-brand flex items-center justify-center text-white text-sm font-bold shadow-lg shadow-orange-500/20 group-hover:scale-110 transition-transform">
                {step.step}
              </div>
              <div className="flex-1 pb-4 border-b border-white/5 last:border-0">
                <div className="flex items-center justify-between mb-1">
                  <h4 className="font-semibold text-sm">{step.title}</h4>
                  {step.duration && (
                    <span className="text-xs text-orange-400 flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      {step.duration}
                    </span>
                  )}
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {step.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Tips */}
      {recipe.tips?.length > 0 && (
        <div className="p-6 rounded-2xl glass border border-white/8">
          <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
            <span className="w-1 h-5 rounded-full gradient-brand" />
            Chef&apos;s Tips
          </h3>
          <div className="grid sm:grid-cols-2 gap-3">
            {recipe.tips.map((tip, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08 }}
                className="p-4 rounded-xl bg-orange-500/8 border border-orange-500/15"
              >
                <h4 className="text-sm font-semibold text-orange-300 mb-1">{tip.title}</h4>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {tip.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      )}
    </motion.div>
  );
}
